name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Use 3.11 for maximum stability
      - name: Install Flet and Build Tools
        run: |
          pip install flet
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
      - name: Build APK
        run: |
          flet build apk --android-permissions android.permission.INTERNET=True android.permission.USE_BIOMETRIC=True
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: finance-app-apk
          path: build/apk/*.apk
